server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    register-with-eureka: false
  instance:
    instance-id: order-service-9001 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以显示ip信息

#开启hystrix支持
feign:
  hystrix:
    enabled: true

info:
  app.name: order-service-9001
  company.name: www.bdqn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: order-service-9001  # 指明微服务应用名，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name。
  profiles:
    active: test #指定日期激活的环境
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd